WIP: async functions to make sure blocks/chunks are loaded
Terasology/ModuleTestingEnvironment pull request #66
Opened 2021-09-08 06:56 UTC by keturn

2021-09-08 11:20 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            if (Thread.currentThread().isInterrupted()) {
ehm.... how current thread can handle this if current thread is interrupted??
there should be try-catch - isn't it?

2021-09-08 11:20 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +                if (!keepRunning && terasologyEngine == host) {
Is host can be shutdown normally?

2021-09-08 20:30 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +                if (!keepRunning && terasologyEngine == host) {
I guess someone could write a test that includes shutdown as expected behavior, but that's pretty different from the MTE tests I've seen so far.

2021-09-08 20:44 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            if (Thread.currentThread().isInterrupted()) {
“Interrupted” in Java threads is a funny thing. As I understand it, [`Thread#interrupt()`][interrupt] does not cause a sudden jump in the code like a POSIX signal in Linux. It only sets a status on the thread to say "hello, I would like you to be interrupted now, please stop—if you feel like it."

Some standard blocking functions like `sleep` and `read` notice this and throw an exception. But if we're just crunching numbers in a loop, there might not be anything that would make us take notice of the interrupt request unless we check for it ourselves.

[interrupt]: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#interrupt() "Thread#interrupt javadoc for Java11"

2021-10-08 20:11 UTC, keturn commented
The required engine PR was merged, so this does build now.

I'm afraid that as much fun as I had writing it, I don't expect this is readable/maintainable for most people: https://github.com/Terasology/ModuleTestingEnvironment/blob/cc33e468c35f8099d7f9d930868caa298a32fd40/src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java#L53-L62  
so I think we had better find another way to write that without the higher-order function gymnastics before merging this one.

2021-10-19 16:26 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            return future.get(0, TimeUnit.SECONDS);
I think the `cancel()` on line 315 is causing the `get()` on 318 to result in this message
> java.util.concurrent.CancellationException: Task was cancelled.

which, despite having something named `cancellationExceptionWithCause` in its stack trace, totally fails to tell us anything about the cause. There's no “due to test safety timeout“ or any helpful message like that.

2021-10-19 16:29 UTC, keturn commented
amidst all the distractions in the test log, there is this:
> [Chunk-Processing-Reactor] ERROR o.t.e.w.c.p.​Chunk­Processing­Pipeline - Cannot run java.​util.​concurrent.​Executor­Completion­Service$​Queueing­Future​@6a1cf258 because queue is full

2021-10-19 20:21 UTC, keturn commented
huh. Only saw that particular "queue full" message once; the later test runs don't have it.

Now this is in the unfortunate position of Works On My Machine, Fails in CI. Which I don't like, but it's also status quo—that's why we have `@Tag("MteTest")`.

While I'd be very happy to see _that_ fixed, I would also be okay with merging this without the Integration Tests stage passing, so that other tests can start using these new functions.

2021-10-19 21:28 UTC, keturn commented on src/test/java/org/terasology/moduletestingenvironment/ChunkRegionFutureTest.java
> +        ChunkRegionFuture chunkRegionFuture = ChunkRegionFuture.create(context, center, sizeInChunks);
This test uses MTEExtension so it can get a Context with a working RelevanceSystem and all. But is it something that could also make use of a stub RelevanceSystem to test something worthwhile?

Might be good to have, especially given that we haven't yet fixed the problems with MTE tests on our CI system.

2021-10-24 17:21 UTC, keturn commented
![](https://github.trello.services/images/mini-trello-icon.png) [new MTE makeBlocksRelevant methods](https://trello.com/c/X0lZ6O7c/188-new-mte-makeblocksrelevant-methods)

2021-10-25 09:15 UTC, DarkWeird requested changes
Tested at FlexibleMovement module - it works (only one engine creating and waiting many generation waiting after every test world purge)

Many checkstyles issue about FIXME and TODO. I guess it will fixed after this PR.
Several JavaDoc's checkstyle issues

2021-10-25 09:15 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +    /** The entity defining the relevance region. */
check style:
`no @return`

2021-10-25 09:15 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +        return chunks;
those chunks should be dense?

2021-10-25 09:15 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +            // FIXME: Document why this IS, in fact, called regularly.
onChunkIrrelevant happens when chunk leave relevant region (entity with Location and Relevant region move away)

2021-10-25 09:15 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            return null;
Can you describe this at javadoc's `@return` line?

2021-10-25 09:15 UTC, DarkWeird commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> -     * @param safetyTimeoutMs
Describe?

2021-10-25 09:15 UTC, DarkWeird commented on src/test/java/org/terasology/moduletestingenvironment/ChunkRegionFutureTest.java
> +        ChunkRegionFuture chunkRegionFuture = ChunkRegionFuture.create(context, center, sizeInChunks);
Why don't use entityManager, relevanceSystem instead?
Context using looks like you want to inject something in context.


Which problem?

2021-10-28 22:38 UTC, keturn commented on src/test/java/org/terasology/moduletestingenvironment/ChunkRegionFutureTest.java
> +        ChunkRegionFuture chunkRegionFuture = ChunkRegionFuture.create(context, center, sizeInChunks);
Really, I want to _use_ the injection system. Some classes, like Test cases and Terasology Systems, get to make references to the things in Context without cluttering up their method signatures.

But I don't know how to get things injected like that when constructing instances of other classes.

Overall, though, I only ended up using two things from the Context, so yeah it's probably worth the cost of one additional argument to remove that confusion.

2021-10-28 22:48 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +            // FIXME: Document why this IS, in fact, called regularly.
That would make sense, but try uncommenting the `logger.warn` here and running the ChunkRegionFutureTest.

_Nothing moves_ in that test, but `onChunkIrrelevant` sure does get called!

2021-10-28 22:57 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +        return chunks;
I don't know what you mean by that.

2021-10-28 23:04 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            return null;
Hmm. I didn't really think about this one.

This was previously a `void` method, so no existing code is using a return value from it.

When I changed this implementation to be on top of `makeBlocksRelevant`, I thought it would make sense to return the value from that (as seen below on line 277).

But it has this early-escape clause where it doesn't call `makeBlocksRelevant` at all.

What would make most sense here?

Leave it always returning `void`?

Remove the `isBlockRelevant` check, and always return the value from makeBlocksRelevant?

2021-10-28 23:14 UTC, keturn commented
@DarkWeird when I [mentioned](https://github.com/Terasology/ModuleTestingEnvironment/pull/66#discussion_r732257021) “we haven't yet fixed the problems with MTE tests on our CI system,” I was referring to the way the Integration Tests have not been passing for a long time: https://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/M/job/ModuleTestingEnvironment/job/develop/

2021-10-28 23:33 UTC, keturn commented on src/test/java/org/terasology/moduletestingenvironment/ChunkRegionFutureTest.java
> +        ChunkRegionFuture chunkRegionFuture = ChunkRegionFuture.create(context, center, sizeInChunks);
fixed to remove the Context reference.

2021-10-28 23:39 UTC, keturn commented
I forwarded some questions about what to do about the JavaDoc to [#documentation](https://discord.com/channels/270264625419911192/822117930501799956/903415821051777074).

2021-11-02 02:22 UTC, keturn reviewed
I also pushed some javadoc syntax corrections.

2021-11-02 02:22 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ChunkRegionFuture.java
> +    /** The entity defining the relevance region. */
[I don't have any good ideas](https://discord.com/channels/270264625419911192/822117930501799956/904894426265055243) about what to do here.

What more information would you like to see about this?

2021-11-02 02:22 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> -     * @param safetyTimeoutMs
I moved more of the above documentation to be within the `@param` block, is that what you were looking for?

2021-11-02 02:23 UTC, keturn commented on src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
> +            return null;
Finding no good way to explain that, I've reverted this back to having no return value.

2021-11-02 07:21 UTC, DarkWeird approved these changes, later dismissed

2021-11-02 16:56 UTC, merged